#
#
#  ____                                   _    _           _       
# | __ ) _   _ _ __   __ _  ___  ___     / \  | | ___ _ __| |_ ___ 
# |  _ \| | | | '_ \ / _` |/ _ \/ _ \   / _ \ | |/ _ \ '__| __/ __|
# | |_) | |_| | | | | (_| |  __/  __/  / ___ \| |  __/ |  | |_\__ \
# |____/ \__,_|_| |_|\__, |\___|\___| /_/   \_\_|\___|_|   \__|___/
#                    |___/                                         
#
#  By GhostAndry Compatible with Vulcan, Matrix and GrimAC
#
#


server_name: "server"

alert_message: "&8[&5&lS&8] &7(%server%) &d%player% &7failed &d%check% &8(&d%vl%&8)"

aclogs:
    enabled: true
    message: "&8[&5&lS&8] &7(%time%) &d%player% &7failed &d%check% &8(&d%vl%&8) &8[&d%server%&8]"
    not-found: "&8[&5&lS&8] &cNessun log trovato per %player%."
    mysql:
        host: "localhost"
        port: 3306
        database: "dragonland"
        username: "dragonland"
        password: "dragonland"