package me.ghostdevelopment.bungeealerts.commands;

import me.ghostdevelopment.bungeealerts.BungeeAlerts;
import me.ghostdevelopment.bungeealerts.utils.Check;
import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.sql.Timestamp;

public class CommandTestalert implements CommandExecutor {

    private final BungeeAlerts plugin = BungeeAlerts.getInstance();

    public CommandTestalert() {}

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (!(sender instanceof Player)) {
            sender.sendMessage("This command can only be used by players.");
            return false;
        }

        Player player = (Player) sender;

        if (!player.hasPermission("bungeealerts.test")) {
            player.sendMessage(ChatColor.RED + "You don't have permission to use this command.");
            return false;
        }

        String serverName = plugin.getConfig().getString("server_name");
        Timestamp now = new Timestamp(System.currentTimeMillis());
        String time = now.toString();
        if (time.length() > 23) time = time.substring(0, 23); // Truncate to 23 chars if needed

        // Create a test Check object
        Check testCheck = new Check(
                time,
                player.getName(),
                "TEST_CHECK",
                5,
                serverName,
                "Test Alert System",
                "This is a test alert generated by the /testalert command\n"
                        + "Player: " + player.getName() + "\n"
                        + "Server: " + serverName + "\n"
                        + "Timestamp: " + time
        );

        // Send the test alert
        BungeeAlerts.getRedisManager().sendCheck(testCheck);

        player.sendMessage(ChatColor.GREEN + "Test alert sent successfully!");
        return true;
    }
}