package me.ghostdevelopment.bungeealerts.commands;

import me.ghostdevelopment.bungeealerts.AlertDispatcher;
import me.ghostdevelopment.bungeealerts.BungeeAlerts;
import me.ghostdevelopment.bungeealerts.Settings;
import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.Player;

/**
 * Sends a test alert through the full dispatch pipeline.
 * <p>
 * Usage: {@code /testalert <player> <check> <vl>}
 * <br>
 * Permission: {@code bungeealerts.test}
 * <p>
 * If no arguments are provided, defaults to the sender's name,
 * check "TEST_CHECK", and VL 5.
 */
public final class CommandTestalert implements CommandExecutor {

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        FileConfiguration config = BungeeAlerts.getInstance().getConfig();

        if (!(sender instanceof Player player)) {
            sender.sendMessage(ChatColor.translateAlternateColorCodes('&',
                    config.getString(Settings.CFG_MSG_PLAYER_ONLY,
                            "&cThis command can only be used by players.")));
            return false;
        }

        if (!player.hasPermission("bungeealerts.test")) {
            sender.sendMessage(ChatColor.translateAlternateColorCodes('&',
                    config.getString(Settings.CFG_MSG_NO_PERMISSION,
                            "&cYou don't have permission to use this command.")));
            return false;
        }

        AlertDispatcher dispatcher = BungeeAlerts.getDispatcher();
        if (dispatcher == null) {
            player.sendMessage(ChatColor.translateAlternateColorCodes('&',
                    config.getString(Settings.CFG_MSG_DISPATCHER_NOT_READY,
                            "&cDispatcher not ready — plugin still starting.")));
            return false;
        }

        String targetPlayer = args.length >= 1 ? args[0] : player.getName();
        String checkName = args.length >= 2 ? args[1].toUpperCase() : "TEST_CHECK";
        int vl = parseVl(args);

        dispatcher.dispatch(
                targetPlayer,
                checkName,
                vl,
                "Test Alert: " + checkName,
                "This is a test alert generated by /testalert\n"
                        + "Player: " + targetPlayer + "\n"
                        + "Check: " + checkName + "\n"
                        + "VL: " + vl
        );

        String successMsg = config.getString(Settings.CFG_MSG_TEST_SENT,
                "&aTest alert sent for %player% (%check% x%vl%)!");
        player.sendMessage(ChatColor.translateAlternateColorCodes('&',
                successMsg
                        .replace("%player%", targetPlayer)
                        .replace("%check%", checkName)
                        .replace("%vl%", String.valueOf(vl))));
        return true;
    }

    private static int parseVl(String[] args) {
        if (args.length < 3) return 5;
        try {
            return Math.max(1, Integer.parseInt(args[2]));
        } catch (NumberFormatException e) {
            return 5;
        }
    }
}
